name: Build and Deploy React App to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install  # Or `yarn install`

      - name: Build React app
        run: |
          npm run build  # Or `yarn build`

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy React App to VPS using Password
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PWD: ${{ secrets.VPS_PWD }}
        run: |
          # Clear out old build files on VPS
          sshpass -p "$VPS_PWD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "rm -rf /var/www/frontend/build/*"
          
          # Deploy new build files to VPS
          sshpass -p "$VPS_PWD" scp -o StrictHostKeyChecking=no -r build/* $VPS_USER@$VPS_HOST:/var/www/frontend/build/
